- name: Change hostname
  hosts: all
  become: yes

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      # when:
      #   ansible_fqdn != inventory_hostname

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state: present
        path: /etc/hosts
        line: "127.0.1.1 {{ inventory_hostname }}"
        search_string: '127.0.1.1'
      # when:
      #   ansible_fqdn != inventory_hostname
        
    - name: Reboot
      ansible.builtin.reboot:

    - name: Validate
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == inventory_hostname